// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PathcordBackend.DbContexts;

#nullable disable

namespace PathcordBackend.Migrations
{
    [DbContext(typeof(PathcordContext))]
    [Migration("20220725154400_UniqueIndexOnChannelDB")]
    partial class UniqueIndexOnChannelDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PathcordBackend.Entities.Channel", b =>
                {
                    b.Property<int>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChannelId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ChannelId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("Ix_Channel_Name");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            ChannelId = 1,
                            Name = "General"
                        },
                        new
                        {
                            ChannelId = 2,
                            Name = "Legendz"
                        });
                });

            modelBuilder.Entity("PathcordBackend.Entities.Subscription", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ChannelId");

                    b.HasIndex("ChannelId");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ChannelId = 1
                        },
                        new
                        {
                            UserId = 1,
                            ChannelId = 2
                        },
                        new
                        {
                            UserId = 2,
                            ChannelId = 1
                        },
                        new
                        {
                            UserId = 3,
                            ChannelId = 1
                        });
                });

            modelBuilder.Entity("PathcordBackend.Entities.TextMessage", b =>
                {
                    b.Property<int>("TextMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TextMessageId"), 1L, 1);

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TextMessageId");

                    b.HasIndex("ChannelId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            TextMessageId = 1,
                            ChannelId = 2,
                            DataStamp = new DateTime(2022, 7, 25, 15, 43, 59, 979, DateTimeKind.Utc).AddTicks(8458),
                            Text = "Hello, World!",
                            UserId = 1
                        },
                        new
                        {
                            TextMessageId = 2,
                            ChannelId = 2,
                            DataStamp = new DateTime(2022, 7, 25, 15, 43, 59, 979, DateTimeKind.Utc).AddTicks(8460),
                            Text = "How are y'all?",
                            UserId = 1
                        },
                        new
                        {
                            TextMessageId = 3,
                            ChannelId = 2,
                            DataStamp = new DateTime(2022, 7, 25, 15, 43, 59, 979, DateTimeKind.Utc).AddTicks(8461),
                            Text = "Pretty good, thanks!",
                            UserId = 2
                        },
                        new
                        {
                            TextMessageId = 4,
                            ChannelId = 1,
                            DataStamp = new DateTime(2022, 7, 25, 15, 43, 59, 979, DateTimeKind.Utc).AddTicks(8462),
                            Text = "Why is this chat so empty?",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("PathcordBackend.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Name = "xMaryx"
                        },
                        new
                        {
                            UserId = 2,
                            Name = "D@mien"
                        },
                        new
                        {
                            UserId = 3,
                            Name = "Le$hawna"
                        });
                });

            modelBuilder.Entity("PathcordBackend.Entities.Subscription", b =>
                {
                    b.HasOne("PathcordBackend.Entities.Channel", "Channel")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PathcordBackend.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PathcordBackend.Entities.TextMessage", b =>
                {
                    b.HasOne("PathcordBackend.Entities.Channel", "Channel")
                        .WithMany("TextMessages")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("PathcordBackend.Entities.Channel", b =>
                {
                    b.Navigation("Subscriptions");

                    b.Navigation("TextMessages");
                });

            modelBuilder.Entity("PathcordBackend.Entities.User", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
